language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
dist: trusty
sudo: required
node_js:
  - "stable"
  - "10"
  - "9"
before_install:
  - npm i -g typescript@latest
  - npm i -g coveralls
install:
  - npm install
script:
  - npm run test
  - npm run docs
  - npm run coverage
after_success: 
  - npm run semantic-release
deploy:
  skip_cleanup: true
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
    condition: $NODE_ENV = production
branches:
  only:
    - master
git:
  depth: 3
  quiet: true
